### ISSUE TITLE
Competitive Analysis

### ISSUE THREAD

**Issue by salmonciara** [hackforla/lucky-parking#237] opened 2021-06-29 03:05 UTC

**Comment by simzou** [comment] 2021-08-04 02:33
Looks like a duplicate of #242

**Closed by simzou** 2021-08-04 02:33 UTC
Labels: status: duplicate

**Comment by salmonciara** [comment] 2021-08-04 02:42
@simzou 

Yen also completed an competitive analysis after I conducted mine. I believe to look at different aspects than I considered. 

You can find that here: https://docs.google.com/spreadsheets/d/15Z6VMJqTrps5G5g-dEY4iEPLjsTdKZ-YFQyrPp-zpU0/edit

This can stay closed though. Thank you for going through the board and cleaning it up!
